set(CMAKE_SYSTEM_NAME               Generic)
set(CMAKE_SYSTEM_PROCESSOR          arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE   STATIC_LIBRARY)

file(TO_CMAKE_PATH $ENV{ARM_GCC_TOOLCHAIN} TOOLCHAIN_PATH)

set(CROSS_PREFIX arm-none-eabi)

set(FILE_EXTENSION "")

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(FILE_EXTENSION ".exe")
endif()

set(CMAKE_AR ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-ar${FILE_EXTENSION})
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-gcc${FILE_EXTENSION})
set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-gcc${FILE_EXTENSION})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-g++${FILE_EXTENSION})
set(CMAKE_SIZE ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-size${FILE_EXTENSION})
set(CMAKE_OBJCOPY ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-objcopy${FILE_EXTENSION})
set(CMAKE_OBJDUMP ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-objdump${FILE_EXTENSION})
set(CMAKE_LINKER ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-g++${FILE_EXTENSION})
set(CMAKE_RANLIB ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-ranlib${FILE_EXTENSION})
set(CMAKE_STRIP ${TOOLCHAIN_PATH}/bin/${CROSS_PREFIX}-strip${FILE_EXTENSION})

set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_PATH} ${TOOLCHAIN_PATH}/${CROSS_PREFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
